apiVersion : apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  labels:
    app   : laravel-app
    env   : prod
    owner : me
spec:
  selector:
    matchLabels:
      project: laravel
  template:
    metadata:
      labels:
        project: laravel
    spec:
      containers:
        - name : laravel
          image: 855659683173.dkr.ecr.eu-west-3.amazonaws.com/php-laravel:latest
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: laravel-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1
    kind: Deployment
    name: laravel-deployment
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: laravel-lb
spec:
  selector:
    project: laravel
  type: LoadBalancer
  ports:
    - name      : laravel-listener
      protocol  : TCP
      port      : 80  # Port on Load Balancer
      targetPort: 80  # Port on Pod
